# Wektorowa reprezentacja tekstu

W najprostszym przypadku budowanie reprezentacji wektorowej polega na zliczaniu ilości słów (ciągów). Każde słowo to atrybut a wartość w danym atrybucie to ilość wystąpniń tego słowa. 


## bag-of-words

Najprostsza reprezentacja to reprezentacja bag-of-words: https://en.wikipedia.org/wiki/Bag-of-words_model. 

Kazdy wektor zapisany jest w rzadkiej reprezentacji jako że słownik może być duży a dokument mały.

# Zad 

* Weźmy tekst i podzielmy na tokeny. 

* Proszę stworzyć słownik słów oraz policzyć częstości każdego słowa. 

* Można użyć Counter - daje nam słownik: https://docs.python.org/2/library/collections.html#collections.Counter


In [1]:
text = "I need to write a program in NLTK that breaks a corpus (a large collection of txt files) into unigrams, bigrams, trigrams, fourgrams and fivegrams. I need to write a program in NLTK that breaks a corpus"
print(text)

I need to write a program in NLTK that breaks a corpus (a large collection of txt files) into unigrams, bigrams, trigrams, fourgrams and fivegrams. I need to write a program in NLTK that breaks a corpus


In [2]:
import nltk
from nltk import word_tokenize
from collections import Counter

tokens = nltk.word_tokenize(text)
unigrams = set(tokens)
print("-----słownik----")
print(unigrams)

-----słownik----
{'need', 'large', 'into', 'a', 'in', 'fourgrams', 'collection', 'and', 'breaks', 'that', 'files', 'of', 'unigrams', ',', 'I', 'txt', 'NLTK', 'write', 'trigrams', 'fivegrams', 'bigrams', 'to', ')', 'program', 'corpus', '.', '('}


In [3]:
print("-----licznik----")
counts1 = Counter(tokens)
print(counts1)

-----licznik----
Counter({'a': 5, ',': 3, 'I': 2, 'need': 2, 'to': 2, 'write': 2, 'program': 2, 'in': 2, 'NLTK': 2, 'that': 2, 'breaks': 2, 'corpus': 2, '(': 1, 'large': 1, 'collection': 1, 'of': 1, 'txt': 1, 'files': 1, ')': 1, 'into': 1, 'unigrams': 1, 'bigrams': 1, 'trigrams': 1, 'fourgrams': 1, 'and': 1, 'fivegrams': 1, '.': 1})


In [5]:
print("-----klucze---")
print(counts1.keys())
print("----wartości--")
print(counts1.values())

-----klucze---
dict_keys(['I', 'need', 'to', 'write', 'a', 'program', 'in', 'NLTK', 'that', 'breaks', 'corpus', '(', 'large', 'collection', 'of', 'txt', 'files', ')', 'into', 'unigrams', ',', 'bigrams', 'trigrams', 'fourgrams', 'and', 'fivegrams', '.'])
----wartości--
dict_values([2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1])


In [6]:
print("--miejsce--")
print(counts1['I'])

--miejsce--
2


# Zad

Zostańmy przy unigramach. Proszę napisać reprezentację bag-of-words własnoręcznie. 

W tym celu:

 * tworzymy słownik słów na podstawie zdanego tekstu (metoda fit)

 * dla stokenizowanego dokumentu, tworzymy macierz częstości

In [7]:
import numpy as np

def fit(tokens):
    words = set(tokens)
    return words

def transform(sentence_words, words):
    # frequency word count
    bag = np.zeros(len(words))
    for sw in sentence_words:
        for i,word in enumerate(words):
            if word == sw: 
                bag[i] += 1
                
    return np.array(bag)

words = fit(tokens)
print(words)
print("--reprezentacja--")
representation = transform(tokens, words)
print(representation)

{'that', 'write', '(', 'NLTK', 'txt', 'unigrams', 'corpus', 'trigrams', 'program', ')', 'fourgrams', ',', 'bigrams', 'need', '.', 'I', 'large', 'collection', 'a', 'files', 'to', 'and', 'fivegrams', 'in', 'breaks', 'into', 'of'}
--reprezentacja--
[2. 2. 1. 2. 1. 1. 2. 1. 2. 1. 1. 3. 1. 2. 1. 2. 1. 1. 5. 1. 2. 1. 1. 2.
 2. 1. 1.]


# ngrams

Teksto można reprezentaować też jako ciągi czyli n-gramy

In [10]:
import nltk
from nltk import word_tokenize
from nltk.util import ngrams
from collections import Counter

In [11]:
text = "I need to write a program in NLTK that breaks a corpus (a large collection of txt files) into unigrams, bigrams, trigrams, fourgrams and fivegrams. I need to write a program in NLTK that breaks a corpus"
print(text)

I need to write a program in NLTK that breaks a corpus (a large collection of txt files) into unigrams, bigrams, trigrams, fourgrams and fivegrams. I need to write a program in NLTK that breaks a corpus


In [13]:
token = nltk.word_tokenize(text)

bigrams = ngrams(token,2)
trigrams = ngrams(token,3)
fourgrams = ngrams(token,4)
fivegrams = ngrams(token,5)

In [14]:
counts2 = Counter(bigrams)
print(counts2)

Counter({('I', 'need'): 2, ('need', 'to'): 2, ('to', 'write'): 2, ('write', 'a'): 2, ('a', 'program'): 2, ('program', 'in'): 2, ('in', 'NLTK'): 2, ('NLTK', 'that'): 2, ('that', 'breaks'): 2, ('breaks', 'a'): 2, ('a', 'corpus'): 2, ('corpus', '('): 1, ('(', 'a'): 1, ('a', 'large'): 1, ('large', 'collection'): 1, ('collection', 'of'): 1, ('of', 'txt'): 1, ('txt', 'files'): 1, ('files', ')'): 1, (')', 'into'): 1, ('into', 'unigrams'): 1, ('unigrams', ','): 1, (',', 'bigrams'): 1, ('bigrams', ','): 1, (',', 'trigrams'): 1, ('trigrams', ','): 1, (',', 'fourgrams'): 1, ('fourgrams', 'and'): 1, ('and', 'fivegrams'): 1, ('fivegrams', '.'): 1, ('.', 'I'): 1})


In [12]:
counts3 = Counter(trigrams)
print(counts3)

Counter({('I', 'need', 'to'): 2, ('need', 'to', 'write'): 2, ('to', 'write', 'a'): 2, ('write', 'a', 'program'): 2, ('a', 'program', 'in'): 2, ('program', 'in', 'NLTK'): 2, ('in', 'NLTK', 'that'): 2, ('NLTK', 'that', 'breaks'): 2, ('that', 'breaks', 'a'): 2, ('breaks', 'a', 'corpus'): 2, ('a', 'corpus', '('): 1, ('corpus', '(', 'a'): 1, ('(', 'a', 'large'): 1, ('a', 'large', 'collection'): 1, ('large', 'collection', 'of'): 1, ('collection', 'of', 'txt'): 1, ('of', 'txt', 'files'): 1, ('txt', 'files', ')'): 1, ('files', ')', 'into'): 1, (')', 'into', 'unigrams'): 1, ('into', 'unigrams', ','): 1, ('unigrams', ',', 'bigrams'): 1, (',', 'bigrams', ','): 1, ('bigrams', ',', 'trigrams'): 1, (',', 'trigrams', ','): 1, ('trigrams', ',', 'fourgrams'): 1, (',', 'fourgrams', 'and'): 1, ('fourgrams', 'and', 'fivegrams'): 1, ('and', 'fivegrams', '.'): 1, ('fivegrams', '.', 'I'): 1, ('.', 'I', 'need'): 1})


In [13]:
counts4 = Counter(fourgrams)
print(counts4)

Counter({('I', 'need', 'to', 'write'): 2, ('need', 'to', 'write', 'a'): 2, ('to', 'write', 'a', 'program'): 2, ('write', 'a', 'program', 'in'): 2, ('a', 'program', 'in', 'NLTK'): 2, ('program', 'in', 'NLTK', 'that'): 2, ('in', 'NLTK', 'that', 'breaks'): 2, ('NLTK', 'that', 'breaks', 'a'): 2, ('that', 'breaks', 'a', 'corpus'): 2, ('breaks', 'a', 'corpus', '('): 1, ('a', 'corpus', '(', 'a'): 1, ('corpus', '(', 'a', 'large'): 1, ('(', 'a', 'large', 'collection'): 1, ('a', 'large', 'collection', 'of'): 1, ('large', 'collection', 'of', 'txt'): 1, ('collection', 'of', 'txt', 'files'): 1, ('of', 'txt', 'files', ')'): 1, ('txt', 'files', ')', 'into'): 1, ('files', ')', 'into', 'unigrams'): 1, (')', 'into', 'unigrams', ','): 1, ('into', 'unigrams', ',', 'bigrams'): 1, ('unigrams', ',', 'bigrams', ','): 1, (',', 'bigrams', ',', 'trigrams'): 1, ('bigrams', ',', 'trigrams', ','): 1, (',', 'trigrams', ',', 'fourgrams'): 1, ('trigrams', ',', 'fourgrams', 'and'): 1, (',', 'fourgrams', 'and', 'fivegra

In [14]:
counts5 = Counter(fivegrams)
print(counts5)

Counter({('I', 'need', 'to', 'write', 'a'): 2, ('need', 'to', 'write', 'a', 'program'): 2, ('to', 'write', 'a', 'program', 'in'): 2, ('write', 'a', 'program', 'in', 'NLTK'): 2, ('a', 'program', 'in', 'NLTK', 'that'): 2, ('program', 'in', 'NLTK', 'that', 'breaks'): 2, ('in', 'NLTK', 'that', 'breaks', 'a'): 2, ('NLTK', 'that', 'breaks', 'a', 'corpus'): 2, ('that', 'breaks', 'a', 'corpus', '('): 1, ('breaks', 'a', 'corpus', '(', 'a'): 1, ('a', 'corpus', '(', 'a', 'large'): 1, ('corpus', '(', 'a', 'large', 'collection'): 1, ('(', 'a', 'large', 'collection', 'of'): 1, ('a', 'large', 'collection', 'of', 'txt'): 1, ('large', 'collection', 'of', 'txt', 'files'): 1, ('collection', 'of', 'txt', 'files', ')'): 1, ('of', 'txt', 'files', ')', 'into'): 1, ('txt', 'files', ')', 'into', 'unigrams'): 1, ('files', ')', 'into', 'unigrams', ','): 1, (')', 'into', 'unigrams', ',', 'bigrams'): 1, ('into', 'unigrams', ',', 'bigrams', ','): 1, ('unigrams', ',', 'bigrams', ',', 'trigrams'): 1, (',', 'bigrams',

# Zad 

Do budowy reprezentacji dla wielu tekstów można użyć sklearn do tej samej czynności:

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize

EXAMPLE_TEXT = "Hello Mr. Smith, how are you doing today? The weather is great, and Python is awesome. The sky is pinkish-blue. You shouldn't eat cardboard. I'm 20 years old."
sentences = sent_tokenize(EXAMPLE_TEXT)

print(sentences)

['Hello Mr. Smith, how are you doing today?', 'The weather is great, and Python is awesome.', 'The sky is pinkish-blue.', "You shouldn't eat cardboard.", "I'm 20 years old."]


In [16]:
vectorizer = CountVectorizer()
vectorizer.fit(sentences)
print( vectorizer.vocabulary_ )

{'hello': 9, 'mr': 12, 'smith': 18, 'how': 10, 'are': 2, 'you': 23, 'doing': 6, 'today': 20, 'the': 19, 'weather': 21, 'is': 11, 'great': 8, 'and': 1, 'python': 15, 'awesome': 3, 'sky': 17, 'pinkish': 14, 'blue': 4, 'shouldn': 16, 'eat': 7, 'cardboard': 5, '20': 0, 'years': 22, 'old': 13}


In [17]:
bag_of_words = vectorizer.transform(sentences)
print(bag_of_words)

  (0, 2)	1
  (0, 6)	1
  (0, 9)	1
  (0, 10)	1
  (0, 12)	1
  (0, 18)	1
  (0, 20)	1
  (0, 23)	1
  (1, 1)	1
  (1, 3)	1
  (1, 8)	1
  (1, 11)	2
  (1, 15)	1
  (1, 19)	1
  (1, 21)	1
  (2, 4)	1
  (2, 11)	1
  (2, 14)	1
  (2, 17)	1
  (2, 19)	1
  (3, 5)	1
  (3, 7)	1
  (3, 16)	1
  (3, 23)	1
  (4, 0)	1
  (4, 13)	1
  (4, 22)	1


In [18]:
print(bag_of_words.todense())

[[0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1]
 [0 1 0 1 0 0 0 0 1 0 0 2 0 0 0 1 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0]]


# Zad:

Możemy tutaj użyć preprocessing i tokenizacje domyślną, ale można też zdefiniować własną.

Proszę użyć wcześniej zdefiniowane funkcje do przetwarzania tekstu w naszym transfromerze - zobacz:

http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

a następnie stworzyć reprezentację **bag-of-words**

In [17]:
from nltk.corpus import stopwords
import string
from nltk.stem import PorterStemmer

#tokenizer działa na tokenach już
def stemming_tokenizer(text):
    tokenized = word_tokenize(text)
    stemmer = PorterStemmer()
    return [stemmer.stem(w) for w in tokenized]

#preprocessor działa na całym dokumencie
def my_preprocessing(word):
    print(word)
    return word

vectorizer = CountVectorizer(preprocessor = my_preprocessing, tokenizer=stemming_tokenizer, stop_words=stopwords.words('english') + list(string.punctuation))

vectorizer.fit(sentences)
print( vectorizer.vocabulary_ )
print(vectorizer.transform(sentences).todense())

(
with
before
now
~
once
himself
of
don't
=
your
re
those
m
own
my
\
both
mightn't
as
these
needn
such
than
very
ours
herself
*
`
am
off
or
haven
mustn
)
but
having
be
it
below
same
needn't
}
about
were
more
hadn't
hasn't
won't
]
ain
{
haven't
!
hasn
over
only
you're
we
their
just
her
so
from
s
that'll
down
should
shouldn't
"
other
;
nor
out
have
and
while
there
has
not
mustn't
.
into
couldn
where
why
them
itself
isn
yours
@
here
this
do
doesn't
hadn
$
:
wasn
what
|
doing
no
yourselves
whom
it's
further
o
he
you'd
between
after
when
'
she
ll
him
didn
d
she's
theirs
myself
against
most
yourself
during
wouldn
aren
%
didn't
ma
-
at
a
had
?
they
who
you'll
through
me
t
doesn
how
<
[
up
mightn
the
you've
some
couldn't
by
is
to
all
_
&
>
aren't
/
weren
ourselves
can
you
its
above
isn't
wouldn't
under
themselves
any
will
if
in
don
should've
that
few
wasn't
then
again
an
been
because
did
i
,
until
on
hers
shouldn
weren't
shan
#
+
won
shan't
^
y
ve
his
which
our
each
was
are
does
for
too
being


C:\Users\admin\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"
C:\Users\admin\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'re", "'s", "'ve", '``', 'abov', 'ani', 'becaus', 'befor', 'could', 'doe', 'dure', 'ha', 'hi', 'might', 'must', "n't", 'need', 'onc', 'onli', 'ourselv', 'sha', 'themselv', 'thi', 'veri', 'wa', 'whi', 'wo', 'would', 'yourselv'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


# Zad 
 
Proszę wykonać podstawową tekenizację biorąc pod uwagę:

 * bierzemy kolejne artykuły i dzieli go na tokeny
 * bierzemy listę tokenów i usuwamy punktory
 * bierzemy listę tokenów i usuwa liczby
 * bierzemy listę tokenów i zamieniamy na małe litery
 
a następnie stworzyć reprezentację **bag-of-words**

In [18]:
import string 
def sen2token(sentence):
    return word_tokenize(sentence)

def remove_punctuation(words):
    remove_list = string.punctuation
    return [w for w in words if not w in set(remove_list)]

def remove_nummbers(words):
    return [w for w in words if not w.isdigit()]

def to_lower(words):
    return [w.lower() for w in words]

def stemming_tokenizer(words):
    words = sen2token(words)
    words = remove_punctuation(words)
    words = remove_nummbers(words)
    words = to_lower(words)
    
    stemmer = PorterStemmer()
    return [stemmer.stem(w) for w in words]

#preprocessor działa na całym dokumencie
def my_preprocessing(word):
    print(word)
    return word

vectorizer = CountVectorizer(tokenizer=stemming_tokenizer, stop_words=stopwords.words('english') + list(string.punctuation))

vectorizer.fit(sentences)
print( vectorizer.vocabulary_ )
print(vectorizer.transform(sentences).todense())


{'hello': 5, 'mr.': 6, 'smith': 12, 'today': 13, 'weather': 14, 'great': 4, 'python': 10, 'awesom': 1, 'sky': 11, 'pinkish-blu': 9, "n't": 7, 'eat': 3, 'cardboard': 2, "'m": 0, 'year': 15, 'old': 8}
[[0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0]
 [0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1]]


C:\Users\admin\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"
C:\Users\admin\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ["'d", "'ll", "'re", "'s", "'ve", '``', 'abov', 'ani', 'becaus', 'befor', 'could', 'doe', 'dure', 'ha', 'hi', 'might', 'must', "n't", 'need', 'onc', 'onli', 'ourselv', 'sha', 'themselv', 'thi', 'veri', 'wa', 'whi', 'wo', 'would', 'yourselv'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


# Zad

Vectorizer buduje nam słownik, czyli definiuje poszczególne wymiary. Mając taki słownik możemy transformować nowe zdania.

Jaką reprezentację będą miały zdania:


 * "The weather is awesome"
 
 * "You shouldn't eat 20 20 30 cardboards"

In [68]:
new_sentences_1 = ["The weather is awesome", "You shouldn't eat 20 20 30 cardboards"]

print(vectorizer.transform(new_sentences_1).todense())

The weather is awesome
You shouldn't eat 20 20 30 cardboards
[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0]]


# Zad 

Jaką reprezentację będą miały zdania zawierające słowo nie występujące wcześniej ("apples"):


 * "You shouldn't eat apples"
 * "Apples apples apples"

In [21]:
new_sentences_2 = ["You shouldn't eat eat apples", "Apples apples apples"]

print(vectorizer.transform(new_sentences_2).todense())

[[0 0 0 2 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
