# Zad. 

Otagować (czyli wskazać słowa "kluczowe") teksty korpusu 20newsgroups

In [1]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')

Wypisz pierwszy tekst

In [2]:
newsgroups_train.data[0]

"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [3]:
print(newsgroups_train.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [4]:
print(len(newsgroups_train.data))

11314


Wypisz tagi (numery) i ich nazwy (napisy) 

In [5]:
print(newsgroups_train.target)
print(len(newsgroups_train.target))
print(len( set( newsgroups_train.target ) ))

[7 4 4 ... 3 1 8]
11314
20


In [6]:
print(len(newsgroups_train.target_names))
newsgroups_train.target_names

20


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

### Można sczytać dane bez nagłówków i stopek

In [7]:
to_remove= ('headers', 'footers', 'quotes')

from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='all', shuffle=True, remove = to_remove)

In [8]:
newsgroups_train.data[0]

"\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n"

In [9]:
print(newsgroups_train.data[0])



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!




In [10]:
newsgroups_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [11]:
print(newsgroups_train.target)

[10  3 17 ...  3  1  7]


In [19]:
data = []
for j in range(len(newsgroups_train.target_names)):
    data.append([newsgroups_train.data[i] for i in range(newsgroups_train.target.shape[0]) if newsgroups_train.target[i] == j])

In [20]:
#biore okreslona ilosc danych z kazdej klasy

categories = 5
num=50
X_set = []
Y_set =[]
for i in range(categories):
    X_set = X_set + data[i][:num]
    Y_set = Y_set + [i]*num

# Zad.

Proszę wykonać podstawową tekenizację biorąc pod uwagę:

 * bierzemy kolejne artykuły i dzieli go na tokeny
 * bierzemy listę tokenów i usuwamy punktory
 * bierzemy listę tokenów i usuwa liczby
 * bierzemy listę tokenów i zamieniamy na małe litery

a następnie stworzyć reprezentację **Tf-Idf**.

Użyj:

```python
from sklearn.feature_extraction.text import TfidfVectorizer
```

In [26]:
from nltk.corpus import stopwords
import string
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

def remove_punctuation(words):
    remove_list = list(string.punctuation) + ["--", "\"", "``" , "...", "''", "'" ]
    return [w for w in words if not w in set(remove_list)]

def remove_nummbers(words):
    return [w for w in words if not w.isdigit()]

def to_lower(words):
    return [w.lower() for w in words]


def my_tokenizer(sent):
    tokens = word_tokenize(sent)
    tokens = remove_punctuation(tokens)
    tokens = remove_nummbers(tokens)
    tokens = to_lower(tokens)
    stemmer = PorterStemmer()
    res = [stemmer.stem(word) for word in tokens]
    return res 


tfidf_vectorizer = TfidfVectorizer(tokenizer=my_tokenizer, stop_words=stopwords.words('english') + list(string.punctuation))
tfidf_matrix = tfidf_vectorizer.fit_transform(X_set)
# print( tfidf_vectorizer.vocabulary_ )

In [27]:
print("----")
print(tfidf_matrix.todense().shape)
print(tfidf_matrix.todense())

----
(250, 4479)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Zad
Wypisz 10 słów kluczowych dla dwóch pierwszych tekstów i sprawdź czy są sensowne.

In [28]:
import numpy as np
for i in range(10):
    print(np.array(tfidf_vectorizer.get_feature_names())[
        tfidf_matrix.getrow(i).todense().argsort().A.flatten()[-10:][::-1]
    ])

['heliocentr' 'galacticentr' 'notion' 'either' 'even' '~330m' 'dream'
 'dragon' 'dram' 'draw']
['moral' 'ask' 'motiv' 'posit' 'correct' 'right' 'percept' 'wrong'
 'question' 'certainli']
['bobbi' 'allah' 'mozumd' 'prove' 'exist' 'mom' 'wisdom' 'men' "'s"
 'contradict']
['possibl' 'lunat' 'liar' 'wa' 'bibl' 'lie' 'die' 'mussolini' 'thousand'
 'unbias']
['bookstor' 'list' 'book' 'find' 'pittsburgh' 'largest' '_any_' 'altern'
 'section' 'area']
['technolog' 'everi' 'must' 'realli' 'etc' 'believ' 'thing' 'crusad'
 '-really-' 'troop']
['jim' 'faith' 'sorri' 'bummin' 'flintston' 'denial' 'chewabl' 'iii'
 'jimmi' 'bye-by']
['yesterday' 'street' 'tien' 'wing' 'einstein' 'lunch' 'fu' 'castro'
 'cooki' 'fortun']
['law' 'islam' 'land' 'religion' 'live' 'life' 'zakat' 'non-muslim'
 'secular' 'popul']
['pope' 'bear' 'wood' 'cathol' 'shit' 'alway' 'thought' 'littl' 'say'
 'becaus']


In [29]:
print(X_set[0])



	There is no notion of heliocentric, or even galacticentric either.



--------------------------------------------------------------------------------


In [30]:
print(X_set[1])

[ . . .]

I am a relativist who would like to answer your question, but the way you
phrase the question makes it unanswerable.  The concepts of "right"
and "wrong" (or "correct/incorrect" or "true/false") belong to the
domain of epistemological rather than moral questions.  It makes no
sense to ask if a moral position is right or wrong, although it is
legitimate to ask if it is good (or better than another position).

Let me illustrate this point by looking at the psychological derivatives
of epistemology and ethics:  perception and motivation, respectively.
One can certainly ask if a percept is "right" (correct, true,
veridical) or "wrong" (incorrect, false, illusory).  But it makes little
sense to ask if a motive is true or false.  On the other hand, it is
strange to ask whether a percept is morally good or evil, but one can
certainly ask that question about motives.

Therefore, your suggested answers (a)-(c) simply can't be considered:
they assume you can judge the correctness of a 