# Wyszukiwanie w tekstach

Kluczowym problemem nlp jest wyszukiwanie podobnych dokumentów.

# Zad 
Prosze wczytać słownik i korpus.

In [1]:
from gensim import corpora, models, similarities, matutils
import numpy as np
import os 

In [2]:
# documents = ["Human machine interface for lab abc computer applications",
#              "A survey of user opinion of computer system response time",
#              "The EPS user interface management system",
#              "System and human system engineering testing of EPS",
#              "Relation of user perceived response time to error measurement",
#              "The generation of random binary unordered trees",
#              "The intersection graph of paths in trees",
#              "Graph minors IV Widths of trees and well quasi ordering",
#               "Graph minors A survey"]

In [14]:
if (os.path.exists("tmp/deerwester.dict")):
    dictionary = corpora.Dictionary.load('tmp/deerwester.dict')
    corpus = corpora.MmCorpus('tmp/deerwester.mm')
    print("Used files generated from first tutorial")
else:
    print("Please run first tutorial to generate data set")



Used files generated from first tutorial


In [4]:
for d in corpus:
    print(d)

[(0, 1.0), (1, 1.0), (2, 1.0)]
[(0, 1.0), (3, 1.0), (4, 1.0), (5, 1.0), (6, 1.0), (7, 1.0)]
[(2, 1.0), (5, 1.0), (7, 1.0), (8, 1.0)]
[(1, 1.0), (5, 2.0), (8, 1.0)]
[(3, 1.0), (6, 1.0), (7, 1.0)]
[(9, 1.0)]
[(9, 1.0), (10, 1.0)]
[(9, 1.0), (10, 1.0), (11, 1.0)]
[(4, 1.0), (10, 1.0), (11, 1.0)]


In [5]:
scipy_csc_matrix = matutils.corpus2csc(corpus)
print(scipy_csc_matrix.todense())

[[1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 2. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [6]:
print(dictionary.token2id)

{'computer': 0, 'human': 1, 'interface': 2, 'response': 3, 'survey': 4, 'system': 5, 'time': 6, 'user': 7, 'eps': 8, 'trees': 9, 'graph': 10, 'minors': 11}


Bierzemy nowy dokument. 

In [7]:
doc = "Human computer interaction"
vec_bow = dictionary.doc2bow(doc.lower().split())
vec_bow

[(0, 1), (1, 1)]

* W gensim najpierw inicjalizujemy query (tworzymy macierz podobieństw) a potem możemy querować podobne dokuenty. 

* Do querowania używane jest podobieństwo cosinusowe.

In [8]:
index = similarities.MatrixSimilarity(corpus)
print(list(index))

[array([0.99999994, 0.23570226, 0.28867513, 0.23570226, 0.        ,
       0.        , 0.        , 0.        , 0.        ], dtype=float32), array([0.23570226, 1.        , 0.4082483 , 0.33333334, 0.70710677,
       0.        , 0.        , 0.        , 0.23570226], dtype=float32), array([0.28867513, 0.4082483 , 1.        , 0.61237246, 0.28867513,
       0.        , 0.        , 0.        , 0.        ], dtype=float32), array([0.23570226, 0.33333334, 0.61237246, 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ], dtype=float32), array([0.        , 0.70710677, 0.28867513, 0.        , 0.99999994,
       0.        , 0.        , 0.        , 0.        ], dtype=float32), array([0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.70710677, 0.57735026, 0.        ], dtype=float32), array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.70710677, 0.99999994, 0.81649655, 0.40824828], dtype=float32), array([0.        , 0.     

In [9]:
sims = index[vec_bow] # perform a similarity query against the corpus
print(list(enumerate(sims))) # print (document_number, document_similarity) 2-tuples

[(0, 0.81649655), (1, 0.28867513), (2, 0.0), (3, 0.28867513), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0)]


# Zad 
Proszę posortować korpus od najbardziej pasujących.

In [10]:
sims = sorted(enumerate(sims), key=lambda item: -item[1])
print(sims) # print sorted (document number, similarity score) 2-tuples

[(0, 0.81649655), (1, 0.28867513), (3, 0.28867513), (2, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0)]


# Zad 
Proszę przanalizować wynik. Jakie dokumenty okazały się najbardziej podobne?

# Zad 
Proszę użyć tfidf do analogicznego zadania. Należy stworzyć odpowiednie funkcje które pozwolą nam yżywać róóżnych transformacji do querowania.

Czy wynik się różni? Co się zmieniło?

In [12]:
tfidf = models.TfidfModel(corpus, id2word=dictionary)
corpus_tfidf = tfidf[corpus]

vec_tfidf = tfidf[vec_bow]

index = similarities.MatrixSimilarity(corpus_tfidf)

sims = index[vec_tfidf]
print(list(enumerate(sims)))

sims = sorted(enumerate(sims), key=lambda item: -item[1])
print(sims)

[(0, 0.81649655), (1, 0.31412902), (2, 0.0), (3, 0.3477732), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0)]
[(0, 0.81649655), (3, 0.3477732), (1, 0.31412902), (2, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0)]


# Zad 

Teraz proszę zrobić to samo z LSI.

In [13]:
lsi = models.LsiModel(corpus, id2word=dictionary, num_topics=2)
vec_lsi = lsi[vec_bow] # convert the query to LSI space

index = similarities.MatrixSimilarity(lsi[corpus])

sims = index[vec_lsi] # perform a similarity query against the corpus
print(list(enumerate(sims)))

sims = sorted(enumerate(sims), key=lambda item: -item[1])
print(sims)

[(0, 0.998093), (1, 0.93748635), (2, 0.9984453), (3, 0.9865886), (4, 0.90755945), (5, -0.12416792), (6, -0.10639259), (7, -0.09879464), (8, 0.050041765)]
[(2, 0.9984453), (0, 0.998093), (3, 0.9865886), (1, 0.93748635), (4, 0.90755945), (8, 0.050041765), (7, -0.09879464), (6, -0.10639259), (5, -0.12416792)]


Proszę zauważyć że w LSI pasujące dokumenty nie muszą zawierać słów które występuja w query. Dlaczego?