# Zad. 

Otagować (czyli wskazać słowa "kluczowe") teksty korpusu 20newsgroups

In [22]:
from gensim import corpora, models, similarities, matutils
import numpy as np
import os 

from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')

Wypisz pierwszy tekst

In [23]:
newsgroups_train.data[0]

"From: lerxst@wam.umd.edu (where's my thing)\nSubject: WHAT car is this!?\nNntp-Posting-Host: rac3.wam.umd.edu\nOrganization: University of Maryland, College Park\nLines: 15\n\n I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.\n\nThanks,\n- IL\n   ---- brought to you by your neighborhood Lerxst ----\n\n\n\n\n"

In [24]:
print(newsgroups_train.data[0])

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







In [25]:
print(len(newsgroups_train.data))

11314


Wypisz tagi (numery) i ich nazwy (napisy) 

In [26]:
print(newsgroups_train.target)
print(len(newsgroups_train.target))
print(len( set( newsgroups_train.target ) ))

[7 4 4 ... 3 1 8]
11314
20


In [27]:
print(len(newsgroups_train.target_names))
newsgroups_train.target_names

20


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

### Można sczytać dane bez nagłówków i stopek

In [28]:
to_remove= ('headers', 'footers', 'quotes')

from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='all', shuffle=True, remove = to_remove)

In [29]:
newsgroups_train.data[0]

"\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n"

In [30]:
print(newsgroups_train.data[0])



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!




In [31]:
newsgroups_train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [32]:
print(newsgroups_train.target)

[10  3 17 ...  3  1  7]


# Zad
Wykonaj przekształcenie Tf-Idf

In [33]:
from nltk.corpus import stopwords
import string
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

def remove_punctuation(words):
    remove_list = list(string.punctuation) + ["--", "\"", "``" , "...", "''", "'" ]
    return [w for w in words if not w in set(remove_list)]

def remove_nummbers(words):
    return [w for w in words if not w.isdigit()]

def to_lower(words):
    return [w.lower() for w in words]


def my_tokenizer(sent):
    tokens = word_tokenize(sent)
    tokens = remove_punctuation(tokens)
    tokens = remove_nummbers(tokens)
    tokens = to_lower(tokens)
    stemmer = PorterStemmer()
    res = [stemmer.stem(word) for word in tokens]
    return res 


tfidf_vectorizer = TfidfVectorizer(tokenizer=my_tokenizer, stop_words=stopwords.words('english') + list(string.punctuation))
tfidf_matrix = tfidf_vectorizer.fit_transform(newsgroups_train.data)
# print( tfidf_vectorizer.vocabulary_ )

In [34]:
print("----")
print(tfidf_matrix.todense().shape)
print(tfidf_matrix.todense())

----
(18846, 175354)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
corpus_sparse = matutils.Sparse2Corpus(tfidf_matrix, documents_columns=False)
dictionary_list = tfidf_vectorizer.get_feature_names()
dictionary_sparse_dict = {i:j for i,j in enumerate(dictionary_list)}
dictionary = corpora.Dictionary.from_corpus(corpus_sparse, id2word=dictionary_sparse_dict)

In [36]:
model = models.LdaModel(corpus=corpus_sparse, id2word=dictionary, num_topics=30)#, alpha='auto', eta='auto', iterations=100)

In [37]:
print(len(model.get_topics()))
model.get_topics()

30


array([[5.5601804e-06, 5.5601804e-06, 5.5601804e-06, ..., 5.5601804e-06,
        5.5601804e-06, 5.5601804e-06],
       [5.6026406e-06, 5.6026406e-06, 5.6026406e-06, ..., 5.6026406e-06,
        5.6026406e-06, 5.6026406e-06],
       [5.6593790e-06, 5.6593790e-06, 5.6593790e-06, ..., 5.6593790e-06,
        5.6593790e-06, 5.6593790e-06],
       ...,
       [3.1723109e-06, 3.1723109e-06, 3.1723109e-06, ..., 3.1723109e-06,
        3.1723109e-06, 3.1723109e-06],
       [5.5977721e-06, 5.5977721e-06, 5.5977721e-06, ..., 5.5977721e-06,
        5.5977721e-06, 5.5977721e-06],
       [5.0928115e-06, 5.0928115e-06, 5.0928115e-06, ..., 5.0928115e-06,
        5.0928115e-06, 5.0928115e-06]], dtype=float32)

In [38]:
import numpy as np

topic_inex = 1
topics = np.argsort(model.get_topics()[topic_inex,:])[::-1] #::-1 sortowanie w odwrotnej kolejności
for x in topics[:5]:
    print(dictionary[x])

a/c
shut
passeng
corvett
pov


In [39]:
model.print_topic(topicno=topic_inex)

'0.001*"a/c" + 0.001*"shut" + 0.001*"passeng" + 0.001*"corvett" + 0.001*"pov" + 0.001*"lopez" + 0.000*"passion" + 0.000*"gamma" + 0.000*"aliv" + 0.000*"ear"'

In [40]:
topic2_terms = model.get_topic_terms(topicid=topic_inex)
topic2_words = [
    (dictionary.get(i), j)
    for i,j in topic2_terms
]
topic2_words

[('a/c', 0.0011800374),
 ('shut', 0.001162108),
 ('passeng', 0.001159218),
 ('corvett', 0.00080142805),
 ('pov', 0.0005473911),
 ('lopez', 0.000509641),
 ('passion', 0.0004916842),
 ('gamma', 0.0004898835),
 ('aliv', 0.00042138502),
 ('ear', 0.00041961911)]

# Wizualizacja modelu LDA:

pyLDAvis

In [41]:
import pyLDAvis.gensim
pyLDAvis.enable_notebook()

In [42]:
pyLDAvis.gensim.prepare(model, corpus_sparse, dictionary)

C:\Users\admin\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:257: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat([default_term_info] + list(topic_dfs))


PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
4      0.361642 -0.079504       1        1  33.157150
17     0.303111 -0.052279       2        1  20.174446
12     0.276155  0.164031       3        1  20.139830
27     0.073545 -0.016831       4        1   4.638849
29    -0.024014 -0.001866       5        1   1.434561
9     -0.025868 -0.001769       6        1   1.337802
14    -0.037839 -0.005113       7        1   1.293606
6     -0.037831  0.000261       8        1   0.994653
18    -0.042960 -0.000249       9        1   0.950634
22    -0.033376 -0.000499      10        1   0.900084
7     -0.038063 -0.000059      11        1   0.870544
20    -0.034639 -0.002013      12        1   0.849006
16    -0.039720 -0.000259      13        1   0.826620
8     -0.039662 -0.001511      14        1   0.815808
21    -0.042129 -0.000383      15        1   0.805184
13    -0.040820  0.000826      16        1   0.795975
5     -0.040910 -0.000832      17        1   0.782658
0     -0.043807  0.000392      18        1   0.758846
10    -0.041163 -0.000267      19        1   0.735156
24    -0.041994 -0.000129      20        1   0.731818
28    -0.041494  0.000044      21        1   0.722856
23    -0.041132 -0.000038      22        1   0.718894
26    -0.039342 -0.000650      23        1   0.716097
15    -0.042308  0.000088      24        1   0.712093
11    -0.039768  0.000936      25        1   0.706948
19    -0.040117 -0.000448      26        1   0.706417
1     -0.040490 -0.000375      27        1   0.698470
3     -0.042206 -0.000021      28        1   0.685971
25    -0.040635 -0.001228      29        1   0.678257
2     -0.042165 -0.000253      30        1   0.660766, topic_info=       Category        Freq       Term       Total  loglift  logprob
term                                                                
166916  Default  136.000000     window  136.000000  30.0000  30.0000
84038   Default  119.000000       file  119.000000  29.0000  29.0000
66678   Default   99.000000       card   99.000000  28.0000  28.0000
154672  Default  170.000000      thank  170.000000  27.0000  27.0000
103203  Default   63.000000        key   63.000000  26.0000  26.0000
134665  Default  111.000000    program  111.000000  25.0000  25.0000
160653  Default  286.000000        use  286.000000  24.0000  24.0000
89325   Default   81.000000     govern   81.000000  23.0000  23.0000
77552   Default   85.000000     driver   85.000000  22.0000  22.0000
76291   Default   65.000000       disk   65.000000  21.0000  21.0000
132668  Default  149.000000      pleas  149.000000  20.0000  20.0000
68195   Default   62.000000       chip   62.000000  19.0000  19.0000
165373  Default  387.000000         wa  387.000000  18.0000  18.0000
87333   Default  124.000000       game  124.000000  17.0000  17.0000
142526  Default  126.000000        run  126.000000  16.0000  16.0000
57664   Default  174.000000      anyon  174.000000  15.0000  15.0000
152459  Default  133.000000     system  133.000000  14.0000  14.0000
80091   Default   75.000000      email   75.000000  13.0000  13.0000
77537   Default  114.000000      drive  114.000000  12.0000  12.0000
89013   Default  159.000000        god  159.000000  11.0000  11.0000
80335   Default   22.000000    encrypt   22.000000  10.0000  10.0000
154019  Default   75.000000       team   75.000000   9.0000   9.0000
148426  Default   66.000000    softwar   66.000000   8.0000   8.0000
112146  Default   63.000000        mac   63.000000   7.0000   7.0000
148646  Default   24.000000       soon   24.000000   6.0000   6.0000
55113   Default   65.000000     advanc   65.000000   5.0000   5.0000
89588   Default   53.000000    graphic   53.000000   4.0000   4.0000
131107  Default  215.000000      peopl  215.000000   3.0000   3.0000
168363  Default   70.000000          x   70.000000   2.0000   2.0000
130658  Default   51.000000         pc   51.000000   1.0000   1.0000
...         ...      