In [32]:
from urllib import request
from bs4 import BeautifulSoup
from urllib.request import urlopen

# Zad
Zczytaj z wikipedi artykuły o tytułach 
```python
["Integral", "Riemann_integral", "Riemann-Stieltjes_integral", "Derivative",
    "Limit_of_a_sequence", "Edvard_Munch", "Vincent_van_Gogh", "Jan_Matejko",
    "Lev_Tolstoj", "Franz_Kafka", "J._R._R._Tolkien"]
```
i zapisz w tablicy zawartości tych podstron ($id="bodyContent"$)

In [33]:
wiki = "http://en.wikipedia.org/wiki/"
titles = ["Integral", "Riemann_integral", "Riemann-Stieltjes_integral", "Derivative",
    "Limit_of_a_sequence", "Edvard_Munch", "Vincent_van_Gogh", "Jan_Matejko",
    "Lev_Tolstoj", "Franz_Kafka", "J._R._R._Tolkien"]



In [34]:
def parse(url):        
    x = urlopen(url).read()
    x = BeautifulSoup(x).find("div",id="bodyContent").find_all("p")
    return(x)

articles = [parse(url) for url in [wiki+x for x in titles]]
articles = [" ".join([str(paragraph) for paragraph in article]) for article in articles]

articles[0][:200]

C:\Users\admin\Anaconda3\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file C:\Users\admin\Anaconda3\lib\runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


'<p>In <a href="/wiki/Mathematics" title="Mathematics">mathematics</a>, an <b>integral</b> assigns numbers to functions in a way that can describe displacement, area, volume, and other concepts that ar'

In [35]:
import re
articles = [re.sub("<.+?>"," ",a) for a in articles] # ew (str(a))

In [36]:
articles[0]

' In  mathematics , an  integral  assigns numbers to functions in a way that can describe displacement, area, volume, and other concepts that arise by combining  infinitesimal  data. Integration is one of the two main operations of  calculus , with its inverse operation,  differentiation , being the other. Given a  function   f  of a  real   variable   x  and an  interval   [ a ,  b ]  of the  real line , the  definite integral \n   is defined informally as the signed  area  of the region in the  xy -plane that is bounded by the  graph  of  f , the  x -axis and the vertical lines   x  =  a   and   x  =  b  . The area above the  x -axis adds to the total and that below the  x -axis subtracts from the total.\n   The operation of integration, up to an additive constant, is the inverse of the operation of differentiation. For this reason, the term  integral  may also refer to the related notion of the  antiderivative , a function  F  whose derivative is the given function  f . In this case

In [37]:
articles[1]

' In the branch of  mathematics  known as  real analysis , the  Riemann integral , created by  Bernhard Riemann , was the first rigorous definition of the  integral  of a  function  on an  interval .  It was presented to the faculty at the  University of Göttingen  in 1854, but not published in a journal until 1868.  [1]   For many functions and practical applications, the Riemann integral can be evaluated by the  fundamental theorem of calculus  or approximated by  numerical integration .\n   The Riemann integral is unsuitable for many theoretical purposes. Some of the technical deficiencies in Riemann integration can be remedied with the  Riemann–Stieltjes integral , and most disappear with the  Lebesgue integral .\n   Let  f  be a non-negative  real -valued function on the interval  [ a ,  b ] , and let\n   be the region of the plane under the graph of the function  f  and above the interval  [ a ,  b ]  (see the figure on the top right). We are interested in measuring the area of  

In [38]:
import numpy as np
with open ('wiki_mycorpus.txt', 'w', encoding="utf-8") as f:
    for el in articles:
        f.write(el)

# Zad

Oczyszczamy tekst:

* tokenizacja

* usuwanie stopwords

* usuwanie tokenów występujących tylko 1 raz

* zmiana dużych liter na małe



In [39]:
from pprint import pprint  # pretty-printer
from collections import defaultdict

# remove common words and tokenize
stoplist = set('for a of the and to in'.split())
texts = [[word for word in articles.lower().split() if word not in stoplist] for articles in articles]

# remove words that appear only once
frequency = defaultdict(int)
for text in texts:
    for token in text:
        frequency[token] += 1

texts = [[token for token in text if frequency[token] > 1]
         for text in texts]
print(len(texts))
pprint(texts)

11
[['mathematics',
  ',',
  'an',
  'integral',
  'assigns',
  'numbers',
  'functions',
  'way',
  'that',
  'can',
  'describe',
  'displacement,',
  'area,',
  'volume,',
  'other',
  'concepts',
  'that',
  'arise',
  'by',
  'combining',
  'infinitesimal',
  'integration',
  'is',
  'one',
  'two',
  'main',
  'operations',
  'calculus',
  ',',
  'with',
  'its',
  'inverse',
  'differentiation',
  ',',
  'being',
  'other.',
  'given',
  'function',
  'f',
  'real',
  'variable',
  'x',
  'an',
  'interval',
  '[',
  ',',
  'b',
  ']',
  'real',
  'line',
  ',',
  'definite',
  'integral',
  'is',
  'defined',
  'as',
  'signed',
  'area',
  'region',
  'that',
  'is',
  'bounded',
  'by',
  'graph',
  'f',
  ',',
  'x',
  '-axis',
  'vertical',
  'lines',
  'x',
  '=',
  'x',
  '=',
  'b',
  '.',
  'area',
  'above',
  'x',
  '-axis',
  'adds',
  'total',
  'that',
  'below',
  'x',
  '-axis',
  'from',
  'operation',
  'integration,',
  'up',
  'an',
  'is',
  'inverse',
  'op

  'with',
  'f',
  '(',
  'x',
  ')',
  '=',
  '√',
  'x',
  '(see',
  'we',
  'call',
  'this',
  'area',
  'integral',
  'f',
  '.',
  'notation',
  'this',
  'integral',
  'will',
  'be',
  'as',
  'first',
  'approximation,',
  'look',
  'at',
  'unit',
  'square',
  'given',
  'by',
  'sides',
  'x',
  '=',
  '0',
  'x',
  '=',
  '1',
  'y',
  '=',
  'f',
  '(0)',
  '=',
  '0',
  'y',
  '=',
  'f',
  '(1)',
  '=',
  '1',
  '.',
  'its',
  'area',
  'is',
  'exactly',
  '1.',
  'true',
  'value',
  'integral',
  'must',
  'be',
  'somewhat',
  'less',
  'than',
  '1.',
  'decreasing',
  'width',
  'approximation',
  'rectangles',
  'increasing',
  'number',
  'rectangles',
  'gives',
  'better',
  'so',
  'cross',
  'interval',
  'five',
  'using',
  'approximation',
  'points',
  '0,',
  'so',
  'on',
  '1.',
  'fit',
  'box',
  'each',
  'step',
  'using',
  'right',
  'end',
  'height',
  'each',
  'curve',
  'piece,',
  'thus',
  '√',
  ',',
  '√',
  ',',
  'so',
  'on',
  '√',

  'differential',
  'forms',
  'makes',
  'sense',
  'arbitrary',
  'dimension',
  'on',
  'more',
  'general',
  'their',
  'higher-dimensional',
  'exterior',
  'derivative',
  'plays',
  'role',
  'gradient',
  'vector',
  'calculus,',
  'theorem',
  'simultaneously',
  'generalizes',
  'three',
  'theorems',
  'vector',
  'theorem',
  ',',
  'theorem',
  ',',
  'theorem',
  '.',
  'discrete',
  'equivalent',
  'integration',
  'is',
  '.',
  'integrals',
  'can',
  'be',
  'put',
  'on',
  'same',
  'foundations',
  'using',
  'theory',
  'lebesgue',
  'integrals',
  'or',
  'time',
  'calculus',
  '.',
  'most',
  'basic',
  'technique',
  'computing',
  'definite',
  'integrals',
  'one',
  'real',
  'variable',
  'is',
  'based',
  'on',
  'fundamental',
  'theorem',
  'calculus',
  '.',
  'let',
  'f',
  '(',
  'x',
  ')',
  'be',
  'function',
  'x',
  'be',
  'integrated',
  'over',
  'given',
  'interval',
  '[',
  ',',
  'b',
  ']',
  '.',
  'then,',
  'find',
  'an',
  'an

  'this',
  'is',
  'case',
  'when',
  'm',
  '=',
  '1',
  ',',
  'so',
  'proof',
  'is',
  'finished',
  'that',
  'case.',
  'therefore,',
  'we',
  'may',
  'assume',
  'that',
  'm',
  '&gt;',
  '1',
  '.',
  'this',
  'case,',
  'it',
  'is',
  'possible',
  'that',
  'one',
  '[',
  'x',
  'i',
  ',',
  'x',
  'i',
  '+',
  '1',
  ']',
  'is',
  'not',
  'contained',
  'any',
  '[',
  'y',
  'j',
  ',',
  'y',
  'j',
  '+',
  '1',
  ']',
  '.',
  'instead,',
  'it',
  'may',
  'across',
  'two',
  'intervals',
  'determined',
  'by',
  'y',
  '0',
  ',',
  '...,',
  'y',
  'm',
  '.',
  '(it',
  'cannot',
  'meet',
  'three',
  'intervals',
  'because',
  'δ',
  'is',
  'assumed',
  'be',
  'smaller',
  'than',
  'length',
  'any',
  'one',
  'it',
  'may',
  'happen',
  'that',
  'may',
  'assume',
  'that',
  'all',
  'inequalities',
  'are',
  'because',
  'otherwise',
  'we',
  'are',
  'previous',
  'case',
  'by',
  'our',
  'on',
  'length',
  'δ',
  '.)',
  'this',
  '

  'integral',
  'is',
  'well-defined',
  'if',
  'f',
  'is',
  'α',
  '-',
  'continuous',
  'g',
  'is',
  'β',
  'continuous',
  'with',
  'α',
  '+',
  'β',
  '&gt;',
  '1.',
  'if',
  'g',
  'is',
  'cumulative',
  'probability',
  'distribution',
  'function',
  'random',
  'variable',
  'x',
  'that',
  'has',
  'probability',
  'density',
  'function',
  'with',
  'respect',
  'lebesgue',
  'measure',
  ',',
  'f',
  'is',
  'any',
  'function',
  'which',
  'expected',
  'value',
  'f',
  '(',
  'x',
  'is',
  'then',
  'probability',
  'density',
  'function',
  'x',
  'is',
  'derivative',
  'g',
  'we',
  'have',
  'but',
  'this',
  'formula',
  'does',
  'not',
  'work',
  'if',
  'x',
  'does',
  'not',
  'have',
  'probability',
  'density',
  'function',
  'with',
  'respect',
  'lebesgue',
  'measure.',
  'particular,',
  'it',
  'does',
  'not',
  'work',
  'if',
  'distribution',
  'x',
  'is',
  'discrete',
  '(i.e.,',
  'all',
  'probability',
  'is',
  'by',
  '

  'derivatives',
  'beyond',
  'this',
  'point,',
  'some',
  'authors',
  'use',
  'roman',
  ',',
  'whereas',
  'others',
  'place',
  'number',
  'latter',
  'notation',
  'generalizes',
  'yield',
  'notation',
  'f',
  '(',
  'n',
  ')',
  '{\\displaystyle',
  'n',
  'th',
  'derivative',
  'f',
  '{\\displaystyle',
  'f}',
  '–',
  'this',
  'notation',
  'is',
  'most',
  'useful',
  'when',
  'we',
  'wish',
  'about',
  'derivative',
  'as',
  'being',
  'function',
  'as',
  'this',
  'case',
  'leibniz',
  'notation',
  'can',
  'become',
  "newton's",
  'notation',
  'differentiation,',
  'also',
  'called',
  'dot',
  'notation,',
  'places',
  'dot',
  'over',
  'function',
  'name',
  'represent',
  'time',
  'derivative.',
  'if',
  'y',
  '=',
  'f',
  '(',
  't',
  ')',
  '{\\displaystyle',
  ',',
  'then',
  'respectively,',
  'first',
  'second',
  'derivatives',
  'y',
  '{\\displaystyle',
  'y}',
  '.',
  'this',
  'notation',
  'is',
  'used',
  'derivatives',


  '.',
  'isaac',
  'newton',
  'gottfried',
  'leibniz',
  'independently',
  'discovered',
  'calculus',
  'century.',
  'however,',
  'each',
  'claimed',
  'other',
  'his',
  'work',
  'bitter',
  'that',
  'continued',
  'until',
  'end',
  'their',
  'lives.'],
 ['as',
  'positive',
  'integer',
  'n',
  '{\\displaystyle',
  'n}',
  'becomes',
  'larger',
  'value',
  'n',
  '⋅',
  'sin',
  '\u2061',
  '(',
  '1',
  'n',
  ')',
  '{\\displaystyle',
  'n\\cdot',
  '\\sin',
  '{\\bigg',
  '(}{\\frac',
  '{1}{n}}{\\bigg',
  ')}}',
  'becomes',
  'arbitrarily',
  'close',
  '1',
  '{\\displaystyle',
  '1}',
  '.',
  'we',
  'say',
  'that',
  '"the',
  'limit',
  'sequence',
  'n',
  '⋅',
  'sin',
  '\u2061',
  '(',
  '1',
  'n',
  ')',
  '{\\displaystyle',
  'n\\cdot',
  '\\sin',
  '{\\bigg',
  '(}{\\frac',
  '{1}{n}}{\\bigg',
  ')}}',
  'equals',
  '1',
  '{\\displaystyle',
  '1}',
  '."',
  'mathematics',
  ',',
  'limit',
  'sequence',
  'is',
  'value',
  'that',
  'terms',
  '

  '[23]',
  'his',
  'idiom',
  'continued',
  'between',
  'naturalistic',
  ',',
  'as',
  'seen',
  'portrait',
  'hans',
  'jæger',
  ',',
  ',',
  'as',
  'rue',
  '.',
  'his',
  'inger',
  'on',
  'beach',
  '(1889),',
  'which',
  'caused',
  'another',
  'storm',
  'confusion',
  'hints',
  'at',
  'simplified',
  'forms,',
  'heavy',
  'emotional',
  'content',
  'his',
  'mature',
  'style',
  '[24]',
  'he',
  'began',
  'carefully',
  'calculate',
  'his',
  'create',
  'emotion.',
  'while',
  'influenced',
  'by',
  ',',
  'what',
  'evolved',
  'was',
  'subject',
  'matter',
  'which',
  'was',
  'symbolist',
  'content,',
  'depicting',
  'state',
  'mind',
  'rather',
  'than',
  'an',
  'external',
  'reality.',
  '1889,',
  'munch',
  'presented',
  'his',
  'first',
  'one-man',
  'show',
  'nearly',
  'all',
  'his',
  'works',
  'recognition',
  'it',
  'received',
  'led',
  'two-year',
  'state',
  'scholarship',
  'study',
  'paris',
  'under',
  'french',
  

  'major',
  'work',
  'norwegian',
  'painting',
  'includes',
  '11',
  'paintings',
  'covering',
  'm',
  '2',
  'sun',
  ',',
  'history',
  'are',
  'key',
  'works',
  'this',
  'sequence.',
  'munch',
  'wanted',
  'form',
  'complete',
  'independent',
  'world',
  'i',
  'wanted',
  'their',
  'visual',
  'expression',
  'be',
  'both',
  'norwegian',
  '2014',
  'it',
  'was',
  'suggested',
  'that',
  'aula',
  'paintings',
  'have',
  'value',
  'at',
  'least',
  'million',
  '[109]',
  '[110]',
  'ashes',
  ',',
  '1894,',
  'oil',
  'on',
  'canvas,',
  '120.5',
  'cm',
  '×',
  'cm',
  '(',
  '47',
  '1',
  '⁄',
  '2',
  '×',
  '55',
  '1',
  '⁄',
  '2',
  'nasjonalgalleriet',
  ',',
  'oslo',
  'dance',
  'life',
  ',',
  'oil',
  'on',
  'canvas,',
  '126',
  'cm',
  '×',
  'cm',
  '(',
  '1',
  '⁄',
  '2',
  '×',
  '75',
  'in),',
  'nasjonalgalleriet',
  ',',
  'oslo',
  'at',
  'table',
  'monte',
  'carlo',
  ',',
  '1892,',
  'cm',
  '×',
  'cm',
  '(',
  '29',

  'father',
  'made',
  'it',
  'clear',
  'that',
  'her',
  'should',
  'be',
  'that',
  'two',
  'would',
  'not',
  'marry,',
  'largely',
  'because',
  'van',
  "gogh's",
  'inability',
  'support',
  'himself.',
  '[62]',
  'mauve',
  'took',
  'van',
  'gogh',
  'on',
  'as',
  'student',
  'introduced',
  'him',
  'which',
  'he',
  'worked',
  'on',
  'next',
  'month',
  'before',
  'returning',
  'home',
  'christmas.',
  '[63]',
  'he',
  'with',
  'his',
  'father,',
  'refusing',
  'attend',
  'church,',
  'left',
  'hague.',
  '[note',
  '[66]',
  'within',
  'month',
  'van',
  'gogh',
  'mauve',
  'fell',
  'out,',
  'possibly',
  'over',
  'drawing',
  'from',
  'plaster',
  '.',
  '[67]',
  'van',
  'gogh',
  'could',
  'only',
  'people',
  'from',
  'street',
  'as',
  'models,',
  'practice',
  'which',
  'mauve',
  'seems',
  'have',
  '[68]',
  'june',
  'van',
  'gogh',
  'suffered',
  'bout',
  'spent',
  'three',
  'weeks',
  'hospital.',
  '[69]',
  'soon'

  'van',
  'gogh',
  'gauguin',
  'both',
  '[142]',
  'van',
  'gogh',
  'was',
  'found',
  'next',
  'morning',
  'by',
  'policeman',
  'taken',
  'hospital,',
  '[145]',
  '[146]',
  'where',
  'félix',
  'young',
  'doctor',
  'still',
  'treated',
  'him.',
  'ear',
  'was',
  'delivered',
  'hospital,',
  'but',
  'rey',
  'did',
  'not',
  'attempt',
  'it',
  'as',
  'too',
  'much',
  'time',
  'had',
  '[140]',
  'van',
  'gogh',
  'had',
  'no',
  'suggesting',
  'that',
  'he',
  'may',
  'have',
  'suffered',
  'an',
  'acute',
  'mental',
  '[147]',
  'hospital',
  'was',
  'with',
  '[148]',
  'within',
  'few',
  'days',
  'local',
  'police',
  'ordered',
  'that',
  'he',
  'be',
  'placed',
  'hospital',
  '[149]',
  '[150]',
  'gauguin',
  'immediately',
  'theo,',
  'who',
  'on',
  '24',
  'december',
  'had',
  'proposed',
  'marriage',
  'his',
  'old',
  'friend',
  'andries',
  'bonger',
  "'s",
  'sister',
  '[151]',
  'that',
  'evening',
  'theo',
  'rush

  ',',
  'paul',
  'signac.',
  'self-portrait',
  'with',
  'grey',
  'felt',
  'hat',
  ',',
  'heavy',
  'paint',
  'spread',
  'across',
  'canvas.',
  'it',
  'is',
  'one',
  'his',
  'most',
  'self-portraits',
  'that',
  'period,',
  '"with',
  'its',
  'highly',
  'organized',
  'brushstrokes,',
  'novel',
  'derived',
  'from',
  'was',
  'what',
  'van',
  'gogh',
  'himself',
  'called',
  'they',
  'contain',
  '[230]',
  'van',
  "gogh's",
  'mental',
  'physical',
  'condition',
  'is',
  'usually',
  'he',
  'may',
  'appear',
  'or',
  'with',
  'neglected',
  'beard,',
  'with',
  'deeply',
  'weak',
  'or',
  'having',
  'lost',
  'some',
  'show',
  'him',
  'with',
  'full',
  'long',
  'face',
  'or',
  'prominent',
  'or',
  'his',
  'hair',
  'may',
  'be',
  'usual',
  'or',
  'at',
  'times',
  '[230]',
  'van',
  "gogh's",
  'is',
  'seldom',
  'directed',
  'at',
  'viewer.',
  'portraits',
  'intensity',
  'colour,',
  'those',
  'painted',
  'after',
  'd

  'pod',
  ').',
  '[11]',
  '[21]',
  'was',
  'gifted',
  'leo',
  'as',
  'polish',
  'matejko,',
  'who',
  'was',
  'one',
  'members',
  'group',
  'delivering',
  'it,',
  'received',
  'knight',
  'commander',
  'with',
  'star',
  'order',
  '.',
  '[26]',
  'painting',
  'is',
  'exhibited',
  'sobieski',
  'room',
  'vatican',
  'museums',
  '.',
  '[27]',
  'at',
  'that',
  'time',
  'he',
  'also',
  'became',
  'vocal',
  'number',
  'political',
  'publishing',
  'letters',
  'on',
  'issues',
  'such',
  'as',
  '.',
  '[26]',
  'another',
  'he',
  'was',
  'very',
  'engaged',
  'were',
  'efforts',
  'various',
  'historical',
  'city',
  'kraków.',
  '[28]',
  '1886,',
  'he',
  'finished',
  'painting',
  'about',
  'french',
  'rather',
  'than',
  'about',
  'polish',
  ',',
  'portraying',
  'joan',
  'arc',
  '.',
  '[26]',
  '[29]',
  'next',
  'year',
  'matejko',
  'received',
  'doctor',
  'philosophy',
  ',',
  'from',
  'jagiellonian',
  'university',
  

  'chapter',
  'confession',
  ',',
  'tolstoy',
  'quoted',
  'final',
  "schopenhauer's",
  'work.',
  'it',
  'explained',
  'how',
  'that',
  'results',
  'from',
  'complete',
  'denial',
  'self',
  'is',
  'only',
  'relative',
  'is',
  'not',
  'be',
  'novelist',
  'was',
  'struck',
  'by',
  'description',
  'buddhist',
  ',',
  'hindu',
  'ascetic',
  'renunciation',
  'as',
  'being',
  'path',
  'after',
  'reading',
  'passages',
  'such',
  'as',
  'which',
  "schopenhauer's",
  'ethical',
  'chapters,',
  'russian',
  'nobleman',
  'chose',
  'poverty',
  'formal',
  'denial',
  'but',
  'this',
  'very',
  'suffering',
  '(by',
  'poor',
  'eternal',
  'is',
  'also',
  'expressed',
  'by',
  'that',
  '(',
  'matthew',
  '"it',
  'is',
  'easier',
  'go',
  'through',
  'eye',
  'than',
  'rich',
  'man',
  'into',
  'kingdom',
  'therefore,',
  'those',
  'who',
  'were',
  'about',
  'their',
  'eternal',
  'chose',
  'voluntary',
  'poverty',
  'when',
  'had',


  'insurance',
  '[46]',
  'he',
  'would',
  'compose',
  'annual',
  'on',
  'insurance',
  'institute',
  'several',
  'years',
  'he',
  'worked',
  'there.',
  'were',
  'received',
  'well',
  'by',
  'his',
  '[47]',
  'kafka',
  'usually',
  'got',
  'off',
  'work',
  'at',
  '2',
  'so',
  'that',
  'he',
  'had',
  'time',
  'spend',
  'on',
  'his',
  'literary',
  'work,',
  'which',
  'he',
  'was',
  'committed.',
  '[48]',
  "kafka's",
  'father',
  'also',
  'expected',
  'him',
  'help',
  'out',
  'at',
  'take',
  'over',
  'family',
  '[49]',
  'his',
  'later',
  'years,',
  "kafka's",
  'illness',
  'often',
  'prevented',
  'him',
  'from',
  'working',
  'at',
  'insurance',
  'at',
  'his',
  'writing.',
  'years',
  'later,',
  'brod',
  'coined',
  'term',
  'der',
  'prager',
  '("the',
  'close',
  'prague',
  'describe',
  'group',
  'writers,',
  'which',
  'included',
  'kafka,',
  'felix',
  'weltsch',
  'him.',
  '[50]',
  '[51]',
  'late',
  '1911,',

  'notebooks',
  'chronological',
  'order.',
  'one',
  'problem',
  'was',
  'that',
  'kafka',
  'often',
  'began',
  'writing',
  'different',
  'parts',
  'sometimes',
  'sometimes',
  'working',
  'from',
  '[169]',
  '[170]',
  'brod',
  'finished',
  'many',
  "kafka's",
  'incomplete',
  'works',
  'publication.',
  'example,',
  'kafka',
  'left',
  'der',
  'process',
  'with',
  'incomplete',
  'das',
  'schloss',
  'with',
  'incomplete',
  'sentences',
  'ambiguous',
  '[170]',
  'brod',
  'rearranged',
  'chapters,',
  'copy',
  'edited',
  'text,',
  'changed',
  'der',
  'process',
  'appeared',
  '1925',
  'verlag',
  'die',
  'schmiede',
  '.',
  'kurt',
  'wolff',
  'published',
  'two',
  'other',
  'das',
  'schloss',
  'amerika',
  '1931,',
  'brod',
  'edited',
  'collection',
  'prose',
  'unpublished',
  'stories',
  'as',
  'der',
  '(the',
  'great',
  ',',
  'including',
  'story',
  'same',
  'name',
  '.',
  'book',
  'appeared',
  'verlag',
  '.',
  "br

  'would',
  'later',
  'inspire',
  'scenes',
  'his',
  'books,',
  'along',
  'with',
  'nearby',
  'towns',
  'such',
  'as',
  ',',
  ',',
  'places',
  'such',
  'as',
  'his',
  'aunt',
  'farm',
  'end,',
  'name',
  'which',
  'he',
  'used',
  'his',
  'fiction.',
  '[20]',
  'mabel',
  'tolkien',
  'taught',
  'her',
  'two',
  'children',
  'at',
  'home.',
  'as',
  'he',
  'was',
  'known',
  'family,',
  'was',
  '[21]',
  'she',
  'taught',
  'him',
  'great',
  'deal',
  'him',
  'look',
  'feel',
  'young',
  'tolkien',
  'liked',
  'draw',
  'landscapes',
  'trees,',
  'but',
  'his',
  'favourite',
  'lessons',
  'were',
  'those',
  'concerning',
  'languages,',
  'his',
  'mother',
  'taught',
  'him',
  'latin',
  'very',
  '[22]',
  'tolkien',
  'could',
  'read',
  'by',
  'age',
  'four',
  'could',
  'write',
  'soon',
  'his',
  'mother',
  'allowed',
  'him',
  'read',
  'many',
  'books.',
  'he',
  'disliked',
  'thought',
  'adventures',
  'by',
  'lewis

  'purely',
  'linguistic',
  'elements.',
  '[76]',
  'at',
  'time,',
  'consensus',
  'scholarship',
  'beowulf',
  'dealing',
  'with',
  'battles',
  'with',
  'monsters',
  'rather',
  'than',
  'realistic',
  'tribal',
  'tolkien',
  'argued',
  'that',
  'author',
  'beowulf',
  'was',
  'human',
  'general,',
  'not',
  'as',
  'limited',
  'by',
  'particular',
  'tribal',
  'therefore',
  'monsters',
  'were',
  'essential',
  'poem.',
  '[77]',
  'where',
  'beowulf',
  'does',
  'deal',
  'with',
  'specific',
  'tribal',
  'struggles,',
  'as',
  'at',
  ',',
  'tolkien',
  'argued',
  'against',
  'reading',
  'fantastic',
  'elements.',
  '[78]',
  'essay,',
  'tolkien',
  'also',
  'revealed',
  'how',
  'highly',
  'he',
  'regarded',
  'beowulf:',
  'is',
  'among',
  'my',
  'most',
  'valued',
  'this',
  'influence',
  'may',
  'be',
  'seen',
  'throughout',
  'his',
  'middle-earth',
  'legendarium',
  '.',
  '[79]',
  'according',
  'humphrey',
  'carpenter',
 

  'tales.',
  'i',
  'do',
  'know',
  'celtic',
  'things',
  'their',
  'original',
  'languages',
  'irish',
  'feel',
  'them',
  'certain',
  'largely',
  'their',
  'fundamental',
  'they',
  'have',
  'bright',
  'colour,',
  'but',
  'are',
  'like',
  'broken',
  'glass',
  'window',
  'without',
  'they',
  'are',
  'fact',
  'as',
  'your',
  'reader',
  'i',
  "don't",
  'believe',
  'i',
  '[147]',
  '[148]',
  'fimi',
  'pointed',
  'out',
  'that',
  'despite',
  'his',
  'dismissive',
  'remarks',
  'about',
  '1937',
  'that',
  'tolkien',
  'was',
  'fluent',
  'medieval',
  'welsh',
  '(though',
  'not',
  'modern',
  'declared',
  'when',
  'delivering',
  'first',
  'lectures',
  'at',
  'oxford',
  '1954',
  'about',
  'influences',
  'celtic',
  'languages',
  'on',
  'english',
  'language',
  'that',
  'is',
  '[145]',
  'one',
  "tolkien's",
  'purposes',
  'when',
  'writing',
  'his',
  'middle-earth',
  'books',
  'was',
  'create',
  'what',
  'his',
  'bi

  'legends.',
  'personally',
  'known',
  'him',
  'were',
  'favourite',
  'illustrator',
  'adventures',
  'tom',
  'bombadil',
  'farmer',
  'giles',
  'ham',
  ')',
  'set',
  'music',
  'road',
  'goes',
  'ever',
  'on',
  ').',
  'queen',
  'ii',
  'created',
  'illustrations',
  'lord',
  'rings',
  'early',
  '1970s.',
  'she',
  'sent',
  'them',
  'tolkien,',
  'who',
  'was',
  'struck',
  'by',
  'similarity',
  'they',
  'bore',
  'style',
  'his',
  'own',
  'drawings.',
  '[189]',
  'however,',
  'tolkien',
  'was',
  'not',
  'fond',
  'all',
  'artistic',
  'representation',
  'his',
  'works',
  'that',
  'were',
  'produced',
  'his',
  'lifetime,',
  'was',
  'sometimes',
  'harshly',
  'he',
  'rejected',
  'illustrations',
  'by',
  'german',
  'edition',
  'hobbit',
  'as',
  '...',
  'bilbo',
  'with',
  'gandalf',
  'as',
  'figure',
  'rather',
  'than',
  'that',
  'i',
  'think',
  '[190]',
  'tolkien',
  'was',
  'tolkien',
  'united',
  '1954',
  'he',
 

# Zad

Proszę 
* utworzyć reprezentację **bag-of-words**
* zapisać w lokalizacji **'/tmp/wiki_deerwester.dict'**


In [1]:
from gensim import corpora


# Zad.

Proszę znaleśc reprezentację nowego dokumentu:

* "Human computer interaction"



In [2]:
new_doc = "Human computer interaction"


# Zad 

Prosze 

* przetransformować cały korpus do postaci wektorowej  
* zapisać go w lokalizacji  **'/tmp/wiki_deerwester.mm'**

# Zad
Proszę wczytać zapisane pliki i wypisać cały korpus w postaci macierzy.

In [45]:
from gensim import corpora, models, similarities, matutils
import os 
if (os.path.exists("tmp/wiki_deerwester.dict")):
    dictionary = corpora.Dictionary.load('tmp/wiki_deerwester.dict')
    corpus = corpora.MmCorpus('tmp/wiki_deerwester.mm')
    print("Used files generated from first tutorial")
else:
    print("Please run first tutorial to generate data set")



Please run first tutorial to generate data set


In [46]:
scipy_csc_matrix = matutils.corpus2csc(corpus)
print(scipy_csc_matrix.todense())

[[ 2.  0.  0. ...  2. 28. 17.]
 [ 2.  0.  0. ...  0.  1.  2.]
 [ 2.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  2.]
 [ 0.  0.  0. ...  0.  0.  3.]
 [ 0.  0.  0. ...  0.  0.  2.]]


# Zad
Wykonaj transformację tfidf. 

Możemy również przetransformować cały korpus.

# Zad

* Wykonaj transformację LSI (2 tematy).

* Wypiszemy jak wyglądają 2 najważniejsze tematy.

# Zad

Proszę posortować artykuły najbardziej pasujące do danego tematu. 

# Zad
Zobaczmy jak wygląda reprezentacja naszych dokumentów.

# Zad 
W zredukowanej przestrzeni proszę zaznaczyć

```python
query = ["Machine Learning", "Mathematics is art"]
```