# Zad. 

Otagować (czyli wskazać słowa "kluczowe", Latent Dirichlet Allocation) teksty korpusu 20newsgroups.

In [2]:
from gensim import corpora, models, similarities, matutils
import numpy as np
import pandas as pd
import os 

### Można sczytać dane bez nagłówków i stopek

In [3]:
df = pd.read_csv('songdata.csv')
df['text'] = df['text'].str.replace('\n', '')
df.head(10)

artist                   song                                        link  \
0   ABBA  Ahe's My Kind Of Girl  /a/abba/ahes+my+kind+of+girl_20598417.html   
1   ABBA       Andante, Andante       /a/abba/andante+andante_20002708.html   
2   ABBA         As Good As New        /a/abba/as+good+as+new_20003033.html   
3   ABBA                   Bang                  /a/abba/bang_20598415.html   
4   ABBA       Bang-A-Boomerang      /a/abba/bang+a+boomerang_20002668.html   
5   ABBA     Burning My Bridges    /a/abba/burning+my+bridges_20003011.html   
6   ABBA              Cassandra             /a/abba/cassandra_20002811.html   
7   ABBA             Chiquitita            /a/abba/chiquitita_20002978.html   
8   ABBA            Crazy World           /a/abba/crazy+world_20003013.html   
9   ABBA        Crying Over You       /a/abba/crying+over+you_20177611.html   

                                                text  
0  Look at her face, it's a wonderful face  And i...  
1  Take it easy with me, please  Touch me gently ...  
2  I'll never know why I had to go  Why I had to ...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...  
5  Well, you hoot and you holler and you make me ...  
6  Down in the street they're all singing and sho...  
7  Chiquitita, tell me what's wrong  You're encha...  
8  I was out with the morning sun  Couldn't sleep...  
9  I'm waitin' for you baby  I'm sitting all alon...

In [5]:
y = df["artist"].values[:1000]
X_set = df["text"].values[:1000]

# Zad
Wykonaj przekształcenie Tf-Idf

```python
from sklearn.feature_extraction.text import TfidfVectorizer
```

In [21]:
from nltk.corpus import stopwords
import string
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

def remove_punctuation(words):
    remove_list =  stopwords.words('english') + list(string.punctuation) + ["'s",'′','--', '."', '!"', '?"', ',"', '``', "''", "\\\\",'⁄',"n't","'ll","'m"]
    return [w for w in words if not w in set(remove_list)]

def remove_nummbers(words):
    return [w for w in words if not w.isdigit()]

def to_lower(words):
    return [w.lower() for w in words]


def my_tokenizer(sent):
    tokens = word_tokenize(sent)
    tokens = to_lower(tokens)    
    tokens = remove_punctuation(tokens)
    tokens = remove_nummbers(tokens)
    stemmer = PorterStemmer()
    res = [stemmer.stem(word) for word in tokens]
    return res 



tfidf_vectorizer = TfidfVectorizer(tokenizer=my_tokenizer, stop_words=stopwords.words('english') + list(string.punctuation))
tfidf_matrix = tfidf_vectorizer.fit_transform(X_set)
# print( tfidf_vectorizer.vocabulary_ )

In [22]:
print("----")
print(tfidf_matrix.todense().shape)
print(tfidf_matrix.todense())

----
(1000, 7123)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Zad 
Stwórz model języka w bibliotece **gensim** na podstawie reprezentacji **Tf-Idf**

In [23]:
corpus_sparse = matutils.Sparse2Corpus(tfidf_matrix, documents_columns=False)
dictionary_list = tfidf_vectorizer.get_feature_names()
dictionary_sparse_dict = {i:j for i,j in enumerate(dictionary_list)}
dictionary = corpora.Dictionary.from_corpus(corpus_sparse, id2word=dictionary_sparse_dict)

# Zad 
Stwórz model **Lda** (Latent Dirichlet Allocation) z
* **num_topics=20**

In [24]:
model = models.LdaModel(corpus=corpus_sparse, id2word=dictionary, num_topics=2)#, alpha='auto', eta='auto', iterations=100)

# Wizualizacja modelu LDA:

pyLDAvis

In [25]:
import pyLDAvis.gensim
pyLDAvis.enable_notebook()

In [ ]:
pyLDAvis.gensim.prepare(model, corpus_sparse, dictionary)