#  Typy danych


##  Tuple ( )

Kolekcja elementów różnego typu. Tuple są ``niezmienne'', tzn nie można ich modyfikować po utworzeniu.

In [37]:
import numpy as np
myTuple = ('abc', np.arange(0,3,0.2), 2.5)
myTuple[2]

2.5

## List []
Kolekcja elementów tego samego typu.
Listy są ``zmienne''', tzn. ich elementy mogą być modyfikowane. Dlatego listy
są zazwyczaj używane do zbierania elementów tego samego typu (liczby, łańcuchy). Zauważmy, że operator "+" łączy listę.

In [38]:
myList = ['abc', 'def', 'ghij']
myList.append('klm')
myList

['abc', 'def', 'ghij', 'klm']

In [39]:
myList2 = [1,2,3]
myList3 = [4,5,6]
myList2 + myList3

[1, 2, 3, 4, 5, 6]

## Array []
Tablice służą do pracy z danymi liczbowymi. Python operuje również na obiektach typu <tt> matrix</tt>. Zaleca się jednak stosowanie tablic, ponieważ wiele bibliotek wymaga obiektów typu <tt> array</tt>

Zauważmy, że listy i tablice 1-d różnią się: 
<ul>
<li> wektory nie można transponować! </li>
<li> operator ``+'' dodaje odpowiednie elementy </li>
<li> operator ``.dot'' wykonuje mnożenie skalarne </li>
<ul>

In [40]:
myArray2 = np.array(myList2)
myArray3 = np.array(myList3)
myArray2 + myArray3

array([5, 7, 9])

In [41]:
myArray2.dot(myArray3)

32

## Dictionary { }

Słowniki są nieuporządkowanymi strukturami danych (kluczowymi/wartościami), w których do elementów odwołujemy się za pomocą: <tt> dict ['key']</tt>. Słowniki można utworzyć za pomocą polecenie <tt> dict </tt> lub używając nawiasów klamrowych <tt> {...}</tt>.

In [42]:
myDict = dict(one=1, two=2, info='some information')
myDict2 = {'ten':1, 'twenty':20,'info':'more information'}
print(myDict['info'])
print(myDict.keys())

some information
dict_keys(['one', 'two', 'info'])


# Zad 2
Napiszmy skrypt który wypisuje:  
<ul>
<li>pierwsze dwa elementy tablicy,</li>
<li>wszystkie po za pierwszymi dwoma elementami tablicy,</li>
<li>tablicę bez ostatnich dwóch elementów,</li>
<li>elementy znajdujące się na parzystych indeksach.</li>
</ul>

In [43]:
import numpy as np
# create a range
x = np.arange(0, 10, 1) # arguments: start, stop, step
print(x)
print(x[0:2])
print(x[:-2])
print(x[2:])
print(x[::2])

[0 1 2 3 4 5 6 7 8 9]
[0 1]
[0 1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# Polecenia najczęściej używane do generowania liczb:
## np.zeros

Generator lablicy zawierającej zera.

In [44]:
import numpy as np
print(np.zeros(3))
print(np.zeros( (2,3) ))

[ 0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


# np.ones
Generator lablicy zawierającej jedynki.

In [45]:
import numpy as np
print(np.ones(3))
print(np.ones((2,3)))

[ 1.  1.  1.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


# np.random.randn
Generator tablicy zawierającej próbkę z rozkładu normalnego o średniej zero i wariancji 1

In [46]:
import numpy as np
print(np.random.randn(10))

[-1.42272538  1.14851565  0.81315572 -1.19581999  1.33866705 -2.67756773
 -0.23345772 -0.53420128  1.43119377  0.42302992]


# np.arange
Generator szeregu liczb. Możemy podać trzy parametry  <tt>start</tt>, <tt>end</tt>, <tt>steppingInterval</tt>. Zauważ, że tablica nie zwiera wartość końcowej (chociaż wygląda to dziwnie to ma tę zaletę, że kolejne sekwencje mogą być łatwo sklejane.

In [47]:
import numpy as np
print(np.arange(3))
print(np.arange(1,3,0.5))
xLow = np.arange(0,3,0.5)
xHigh = np.arange(3,5,0.5)
print(xLow)
print(xHigh)
print(np.concatenate((np.arange(1,3,0.5),np.arange(3,5,0.5))))
print(np.arange(1,5,0.5))

[0 1 2]
[ 1.   1.5  2.   2.5]
[ 0.   0.5  1.   1.5  2.   2.5]
[ 3.   3.5  4.   4.5]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5]


# np.linspace
Generuje liniowo rozmieszczonych liczby.

In [48]:
import numpy as np
print(np.linspace(0,10,6))
print(np.linspace(2.0, 3.0, num=5, endpoint=False))
print(np.linspace(2.0, 3.0, num=5, retstep=True))

[  0.   2.   4.   6.   8.  10.]
[ 2.   2.2  2.4  2.6  2.8]
(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)


# np.array
Generuje tablicę numpy z danych liczbowych.

In [51]:
Amat = np.array([ [1, 2], [3, 4] ])
print(Amat)

[[1 2]
 [3 4]]


Wektory są po prostu "listami list". Dlatego też pierwszy element zwraca pierwszy wiersz

In [ ]:
Amat = np.array([ [1, 2], [3, 4] ])
print(Amat)
print(Amat[0])

Wektor nie jest tym samym co macierz jednowymiarowa. Jest to jeden z niewielu nieintuicyjnych funkcji i może prowadzić do błędów, które trudno znaleźć. Na przykład wektory nie mogą być transponowane a macierze mogą.

In [50]:
x = np.arange(3)
print(x)
print(type(x))
Amat = np.array([ [1,2], [3,4] ])
print(Amat)
print(type(Amat))
print(x.T == x)
print(Amat.T == Amat)

[0 1 2]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
[ True  True  True]
[[ True False]
 [False  True]]
